### see all games
GET http://localhost:8080/games

### see games available for a tier

GET http://localhost:8080/games
    ?tier=3

### search game by id

GET http://localhost:8080/games
    ?id=67d889d2d070de1600cf2b48

### search game by title

GET http://localhost:8080/games
    ?title=Half-Life

### search game by title and tier

GET http://localhost:8080/games
    ?title=Half-Life
    &tier=2

### add a game
@game_name = Half-Life:Alyx
@game_tier = 3
POST http://localhost:8080/add-game
    ?title={{game_name}}
    &tier={{game_tier}}

### delete a game

POST http://localhost:8080/delete-game
    ?id=67d892cdb65bb038c7c6302a