POST http://localhost:8080/student/create?name=Ion Popescu&email=ion.popescu@gmail.com&age=22&grades=9&grades=8

# DELETE http://localhost:8080/student/delete?id=641d5d9665e94170beddd454

# GET http://localhost:8080/student/getAll

# GET http://localhost:8080/student/sortByAge


