### see all games
GET http://localhost:8080/games

### see games available for a tier

GET http://localhost:8080/games
    ?tier=1

### search game by id

GET http://localhost:8080/games
    ?id=67ec2d8ebda3e0505ab4c5e2

### search game by title

GET http://localhost:8080/games
    ?title=Half-Life

### search game by title and tier

GET http://localhost:8080/games
    ?title=Half-Life
    &tier=1

### add a game
@game_name = Counter-Strike
@game_tier = 1
POST http://localhost:8080/add-game
    ?title={{game_name}}
    &tier={{game_tier}}

### delete a game

POST http://localhost:8080/delete-game
    ?id=67ec2d8ebda3e0505ab4c5e2

### get account info

GET http://localhost:8080/account
    ?username=Ionel
    &password=parola3

### see available subscription upgrades
GET http://localhost:8080/seeUpgrades
    ?username=Ionel
    &password=parola3

### upgrade to a target tier

POST http://localhost:8080/upgradeTier
    ?username=Ionel
    &password=parola3
    &tier=2

### cancel your subscrption

POST http://localhost:8080/cancelSubscription
    ?username=Ionel
    &password=parola3