### SUBSCRIPTIONS ###

### Get all subscriptions

GET http://localhost:8080/subscriptions

### Get subscription by ID

GET http://localhost:8080/subscriptions
    ?id=12345

### Get subscriptions by tier

GET http://localhost:8080/subscriptions
    ?tier=2

### Get subscriptions by max price

GET http://localhost:8080/subscriptions
    ?price=100

### Get subscriptions by tier and max price

GET http://localhost:8080/subscriptions
    ?tier=2
    &price=100

### GET /subscriptions/uptotier

GET http://localhost:8080/subscriptions/uptotier
    ?tier=3

### POST /add-subscription

POST http://localhost:8080/add-subscription
    ?tier=2
    &price=99

### POST /delete-subscription

POST http://localhost:8080/delete-subscription
    ?id=12345

