server.port=8080
spring.application.name=prod-eng-service
mongodb.connection.url=${MONGODB_CONECTION_URL:mongodb://root:example@localhost:27017}

app.jwt.secret=/uQ+Lkq9aoVb+pg04NFxVhvPBLRHqzPT8boTRtbHMjw=
app.jwt.expiration-ms=86400000