apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    slots-service: slots
  name: slots

spec:
  replicas: 1
  selector:
    matchLabels:
      slots-service: slots

  template:
    metadata:
      labels:
        slots-service: slots

    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: ENVIRONMENT_NAME
              value: local
            - name: MONGODB_CONECTION_URL
              value: mongodb://root:example@mongo:27017/
          image: robertpoziumschi/slots-img-pipeline:v1.2.0
          name: slots
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service

metadata:
  labels:
    slots-service: slots
  name: slots

spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    slots-service: slots
