apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://host.docker.internal:3100
    basicAuth: false
    isDefault: false
    editable: true
