pipeline {
    agent any
    environment {
        DOCKER_CREDS = credentials("docker_password")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Tag image') {
            steps {
                script {
                    GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                    MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                    MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                    PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()
                }
                sh "docker build -t ${DOCKER_CREDS_USR}/triplea-img:${MAJOR_VERSION}.\$(({MINOR_VERSION} + 1)).${PATCH_VERSION} ."
            }
        }

        stage('Push image') {
            steps {
                sh "echo ${DOCKER_CREDS_USR} | docker login -u ${DOCKER_CREDS_USR} -p ${DOCKER_CREDS_PSW}"
                sh "docker ${DOCKER_CREDS_USR}/triplea-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION}"
            }
        }
    }
}
